version: '3.8'

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/readally-backend:latest
    container_name: readally-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./readally.db:/app/readally.db
    env_file:
      - .env

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/readally-frontend:latest
    container_name: readally-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
